# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
exclude:          ["vendor"]
title:            John F. Nixon
tagline:          Nonrandom things I don't want to forget
url:              http://blog.johnfnixon.com
paginate:         5
baseurl:          /
author:
  name:           John F. Nixon
  url:            https://twitter.com/jfnixon
  email:          john@johnfnixon.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jfnixon/jfnixon.github.io
